/**
 * Design Tokens Generator — BuilderPro
 *
 * Generates a design tokens file from project branding + BuilderPro defaults.
 * Output format varies by export target:
 *   - React / Vue (TS): tokens.ts  — named TS exports
 *   - React / Vue (JS): tokens.js  — named JS exports
 *   - Angular:          tokens.scss — SCSS variables
 *   - HTML:             tokens.css  — CSS custom properties
 */

import type { BuilderMode } from '@/types/builder.types'
import type { OutputPlatform, ProjectBranding } from '@/types/store.types'

export interface DesignTokenSet {
  // Colors
  colorPrimary: string
  colorSecondary: string
  colorAccent: string
  colorDanger: string
  colorBackground: string
  colorSurface: string
  colorBorder: string
  colorTextPrimary: string
  colorTextSecondary: string
  // Typography
  fontPrimary: string
  fontSizeXs: string
  fontSizeSm: string
  fontSizeBase: string
  fontSizeLg: string
  fontSizeXl: string
  fontSize2xl: string
  fontSize3xl: string
  // Spacing
  spacing1: string
  spacing2: string
  spacing3: string
  spacing4: string
  spacing6: string
  spacing8: string
  spacing12: string
  spacing16: string
  // Border radius
  radiusSm: string
  radiusMd: string
  radiusLg: string
  radiusXl: string
  radius2xl: string
  // Breakpoints
  breakpointMobile: string
  breakpointTablet: string
  breakpointDesktop: string
}

const DEFAULTS: DesignTokenSet = {
  colorPrimary:        '#4F46E5',
  colorSecondary:      '#06B6D4',
  colorAccent:         '#22C55E',
  colorDanger:         '#EF4444',
  colorBackground:     '#FFFFFF',
  colorSurface:        '#F8FAFC',
  colorBorder:         '#E2E8F0',
  colorTextPrimary:    '#0F172A',
  colorTextSecondary:  '#475569',
  fontPrimary:         'Inter, sans-serif',
  fontSizeXs:          '12px',
  fontSizeSm:          '14px',
  fontSizeBase:        '16px',
  fontSizeLg:          '18px',
  fontSizeXl:          '24px',
  fontSize2xl:         '32px',
  fontSize3xl:         '48px',
  spacing1:            '4px',
  spacing2:            '8px',
  spacing3:            '12px',
  spacing4:            '16px',
  spacing6:            '24px',
  spacing8:            '32px',
  spacing12:           '48px',
  spacing16:           '64px',
  radiusSm:            '4px',
  radiusMd:            '8px',
  radiusLg:            '12px',
  radiusXl:            '16px',
  radius2xl:           '24px',
  breakpointMobile:    '390px',
  breakpointTablet:    '768px',
  breakpointDesktop:   '1440px',
}

/** Merge project branding over defaults to get the final token set */
function resolveTokens(branding?: ProjectBranding): DesignTokenSet {
  const tokens = { ...DEFAULTS }
  if (branding?.primaryColor) tokens.colorPrimary = branding.primaryColor
  if (branding?.fontFamily)   tokens.fontPrimary  = `${branding.fontFamily}, sans-serif`
  return tokens
}

// ─── TypeScript output ───────────────────────────────────────────────────────

function toTS(tokens: DesignTokenSet): string {
  const entries = Object.entries(tokens)
    .map(([k, v]) => `  ${k}: '${v}',`)
    .join('\n')
  return `/**
 * Design Tokens — generated by BuilderPro
 * These values reflect your project's branding and BuilderPro design system.
 */
export const tokens = {
${entries}
} as const

export type DesignTokens = typeof tokens
`
}

// ─── JavaScript output ───────────────────────────────────────────────────────

function toJS(tokens: DesignTokenSet): string {
  const entries = Object.entries(tokens)
    .map(([k, v]) => `  ${k}: '${v}',`)
    .join('\n')
  return `/**
 * Design Tokens — generated by BuilderPro
 */
export const tokens = {
${entries}
}
`
}

// ─── SCSS output ─────────────────────────────────────────────────────────────

function toKebab(camel: string): string {
  return camel.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

function toSCSS(tokens: DesignTokenSet): string {
  const vars = Object.entries(tokens)
    .map(([k, v]) => `$${toKebab(k)}: ${v};`)
    .join('\n')
  return `// Design Tokens — generated by BuilderPro
// Import this file in styles.scss: @use 'tokens' as *;

${vars}
`
}

// ─── CSS custom properties output ────────────────────────────────────────────

function toCSS(tokens: DesignTokenSet): string {
  const vars = Object.entries(tokens)
    .map(([k, v]) => `  --${toKebab(k)}: ${v};`)
    .join('\n')
  return `/* Design Tokens — generated by BuilderPro */
:root {
${vars}
}
`
}

// ─── Public API ──────────────────────────────────────────────────────────────

export interface TokensFile {
  filename: string
  content: string
}

export function generateTokensFile(params: {
  branding: ProjectBranding | undefined
  platform: OutputPlatform
  lang: 'typescript' | 'javascript'
}): TokensFile {
  const { branding, platform, lang } = params
  const tokens = resolveTokens(branding)

  if (platform === 'angular') {
    return { filename: 'src/tokens.scss', content: toSCSS(tokens) }
  }

  if (platform === 'html') {
    return { filename: 'tokens.css', content: toCSS(tokens) }
  }

  // React / Vue
  if (lang === 'javascript') {
    return { filename: 'src/tokens.js', content: toJS(tokens) }
  }
  return { filename: 'src/tokens.ts', content: toTS(tokens) }
}

/** Expose resolved token set for use in README generator */
export function resolveDesignTokens(branding?: ProjectBranding): DesignTokenSet {
  return resolveTokens(branding)
}
